using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Snipper
{
    internal static class Constants
    {
        public const int WM_HOTKEY = 0x0312;
        public const int CAP_WINDOW_HOTKEY = 1;
        public const int CAP_AREA_HOTKEY = 2;

        public const string APP_GUID = "f2d44a6c-b312-430d-b18c-914e8cbe11b2";
        public const string SETTINGS_FILE_NAME = "settings.xml";

        public const string SETTINGS_TAG = "settings";
        public const string SAVE_DIR_TAG = "savedir";
        public const string SEL_CAP_HKEY_TAG = "selcaphkey";
        public const string WIN_CAP_HKEY_TAG = "wincaphkey";
        public const string COPY_CLIP_TAG = "docopyclip";
        public const string SAVE_IMAGE_TAG = "dosaveimage";
        public const string MODIFIERS_TAG = "mod";
        public const string KEY_TAG = "key";



        public static Dictionary<uint, string> vkeyMap;
        static Constants() 
        {
            vkeyMap = new Dictionary<uint, string>();
            vkeyMap[0x0C] = "Clear";
            vkeyMap[0x12] = "Menu";
            vkeyMap[0x13] = "Pause";
            vkeyMap[0x15] = "Kana";
            vkeyMap[0x15] = "Hangeul";
            vkeyMap[0x15] = "Hangul";
            vkeyMap[0x17] = "Junja";
            vkeyMap[0x18] = "Final";
            vkeyMap[0x19] = "Hanja";
            vkeyMap[0x19] = "Kanji";
            vkeyMap[0x1C] = "Convert";
            vkeyMap[0x1D] = "NonConvert";
            vkeyMap[0x1E] = "Accept";
            vkeyMap[0x1F] = "ModeChange";
            vkeyMap[0x20] = "Space";
            vkeyMap[0x21] = "Prior";
            vkeyMap[0x22] = "Next";
            vkeyMap[0x23] = "End";
            vkeyMap[0x24] = "Home";
            vkeyMap[0x25] = "Left";
            vkeyMap[0x26] = "Up";
            vkeyMap[0x27] = "Right";
            vkeyMap[0x28] = "Down";
            vkeyMap[0x29] = "Select";
            vkeyMap[0x2A] = "Print";
            vkeyMap[0x2B] = "Execute";
            vkeyMap[0x2C] = "Snapshot";
            vkeyMap[0x2D] = "Insert";
            vkeyMap[0x2E] = "Delete";
            vkeyMap[0x2F] = "Help";
            vkeyMap[0x30] = "0";
            vkeyMap[0x31] = "1";
            vkeyMap[0x32] = "2";
            vkeyMap[0x33] = "3";
            vkeyMap[0x34] = "4";
            vkeyMap[0x35] = "5";
            vkeyMap[0x36] = "6";
            vkeyMap[0x37] = "7";
            vkeyMap[0x38] = "8";
            vkeyMap[0x39] = "9";
            vkeyMap[0x41] = "A";
            vkeyMap[0x42] = "B";
            vkeyMap[0x43] = "C";
            vkeyMap[0x44] = "D";
            vkeyMap[0x45] = "E";
            vkeyMap[0x46] = "F";
            vkeyMap[0x47] = "G";
            vkeyMap[0x48] = "H";
            vkeyMap[0x49] = "I";
            vkeyMap[0x4A] = "J";
            vkeyMap[0x4B] = "K";
            vkeyMap[0x4C] = "L";
            vkeyMap[0x4D] = "M";
            vkeyMap[0x4E] = "N";
            vkeyMap[0x4F] = "O";
            vkeyMap[0x50] = "P";
            vkeyMap[0x51] = "Q";
            vkeyMap[0x52] = "R";
            vkeyMap[0x53] = "S";
            vkeyMap[0x54] = "T";
            vkeyMap[0x55] = "U";
            vkeyMap[0x56] = "V";
            vkeyMap[0x57] = "W";
            vkeyMap[0x58] = "X";
            vkeyMap[0x59] = "Y";
            vkeyMap[0x5A] = "Z";
            vkeyMap[0x5D] = "Application";
            vkeyMap[0x5F] = "Sleep";
            vkeyMap[0x60] = "N0";
            vkeyMap[0x61] = "N1";
            vkeyMap[0x62] = "N2";
            vkeyMap[0x63] = "N3";
            vkeyMap[0x64] = "N4";
            vkeyMap[0x65] = "N5";
            vkeyMap[0x66] = "N6";
            vkeyMap[0x67] = "N7";
            vkeyMap[0x68] = "N8";
            vkeyMap[0x69] = "N9";
            vkeyMap[0x6A] = "N*";
            vkeyMap[0x6B] = "N+";
            vkeyMap[0x6C] = "\\";
            vkeyMap[0x6D] = "N-";
            vkeyMap[0x6E] = "N.";
            vkeyMap[0x6F] = "N/";
            vkeyMap[0x70] = "F1";
            vkeyMap[0x71] = "F2";
            vkeyMap[0x72] = "F3";
            vkeyMap[0x73] = "F4";
            vkeyMap[0x74] = "F5";
            vkeyMap[0x75] = "F6";
            vkeyMap[0x76] = "F7";
            vkeyMap[0x77] = "F8";
            vkeyMap[0x78] = "F9";
            vkeyMap[0x79] = "F10";
            vkeyMap[0x7A] = "F11";
            vkeyMap[0x7B] = "F12";
            vkeyMap[0x7C] = "F13";
            vkeyMap[0x7D] = "F14";
            vkeyMap[0x7E] = "F15";
            vkeyMap[0x7F] = "F16";
            vkeyMap[0x80] = "F17";
            vkeyMap[0x81] = "F18";
            vkeyMap[0x82] = "F19";
            vkeyMap[0x83] = "F20";
            vkeyMap[0x84] = "F21";
            vkeyMap[0x85] = "F22";
            vkeyMap[0x86] = "F23";
            vkeyMap[0x87] = "F24";
            vkeyMap[0x90] = "NumLock";
            vkeyMap[0x91] = "ScrollLock";
            vkeyMap[0x92] = "NEC_Equal";
            vkeyMap[0x92] = "Fujitsu_Jisho";
            vkeyMap[0x93] = "Fujitsu_Masshou";
            vkeyMap[0x94] = "Fujitsu_Touroku";
            vkeyMap[0x95] = "Fujitsu_Loya";
            vkeyMap[0x96] = "Fujitsu_Roya";
            vkeyMap[0xA6] = "BrowserBack";
            vkeyMap[0xA7] = "BrowserForward";
            vkeyMap[0xA8] = "BrowserRefresh";
            vkeyMap[0xA9] = "BrowserStop";
            vkeyMap[0xAA] = "BrowserSearch";
            vkeyMap[0xAB] = "BrowserFavorites";
            vkeyMap[0xAC] = "BrowserHome";
            vkeyMap[0xAD] = "VolumeMute";
            vkeyMap[0xAE] = "VolumeDown";
            vkeyMap[0xAF] = "VolumeUp";
            vkeyMap[0xB0] = "MediaNextTrack";
            vkeyMap[0xB1] = "MediaPrevTrack";
            vkeyMap[0xB2] = "MediaStop";
            vkeyMap[0xB3] = "MediaPlayPause";
            vkeyMap[0xB4] = "LaunchMail";
            vkeyMap[0xB5] = "LaunchMediaSelect";
            vkeyMap[0xB6] = "LaunchApplication1";
            vkeyMap[0xB7] = "LaunchApplication2";
            vkeyMap[0xBA] = "OEM1";
            vkeyMap[0xBB] = "OEMPlus";
            vkeyMap[0xBC] = "OEMComma";
            vkeyMap[0xBD] = "OEMMinus";
            vkeyMap[0xBE] = "OEMPeriod";
            vkeyMap[0xBF] = "OEM2";
            vkeyMap[0xC0] = "OEM3";
            vkeyMap[0xDB] = "OEM4";
            vkeyMap[0xDC] = "OEM5";
            vkeyMap[0xDD] = "OEM6";
            vkeyMap[0xDE] = "OEM7";
            vkeyMap[0xDF] = "OEM8";
            vkeyMap[0xE1] = "OEMAX";
            vkeyMap[0xE2] = "OEM102";
            vkeyMap[0xE3] = "ICOHelp";
            vkeyMap[0xE4] = "ICO00";
            vkeyMap[0xE5] = "ProcessKey";
            vkeyMap[0xE6] = "ICOClear";
            vkeyMap[0xE7] = "Packet";
            vkeyMap[0xE9] = "OEMReset";
            vkeyMap[0xEA] = "OEMJump";
            vkeyMap[0xEB] = "OEMPA1";
            vkeyMap[0xEC] = "OEMPA2";
            vkeyMap[0xED] = "OEMPA3";
            vkeyMap[0xEE] = "OEMWSCtrl";
            vkeyMap[0xEF] = "OEMCUSel";
            vkeyMap[0xF0] = "OEMATTN";
            vkeyMap[0xF1] = "OEMFinish";
            vkeyMap[0xF2] = "OEMCopy";
            vkeyMap[0xF3] = "OEMAuto";
            vkeyMap[0xF4] = "OEMENLW";
            vkeyMap[0xF5] = "OEMBackTab";
            vkeyMap[0xF6] = "ATTN";
            vkeyMap[0xF7] = "CRSel";
            vkeyMap[0xF8] = "EXSel";
            vkeyMap[0xF9] = "EREOF";
            vkeyMap[0xFA] = "Play";
            vkeyMap[0xFB] = "Zoom";
            vkeyMap[0xFC] = "Noname";
            vkeyMap[0xFD] = "PA1";
            vkeyMap[0xFE] = "OEMClear";
        }
    }
}
